signup/signup/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('signupApp.urls')),
    url(r'^admin/', admin.site.urls),
]

signup/signupApp/urls.py
from django.conf.urls import url
from . import views

app_name = "signupApp"
urlpatterns = [
    url(r'^login/$', views.login, name="login"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^home/$', views.contacts, name="home"),
    url(r'^contacts/$', views.contacts, name="contacts"),
    url(r'^logout/$', views.logout, name="logout"),
]

signup/signupApp/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=200)
    gender_list = (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=1, choices=gender_list)
    mobile_no = models.CharField(max_length=10)
    email_id = models.CharField(max_length=300)
    password = models.CharField(max_length=25, default="")


class Contact_List(models.Model):
    contact_from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contact_from_user_id', null=True)
    contact_to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contact_to_user_id', null=True)
    status_list = (('r', 'request'), ('f', 'friend'))
    status = models.CharField(max_length=1, choices=status_list)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now=True)


class Chat(models.Model):
    chat_from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chat_from_user_id', null=True)
    chat_to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chat_to_user_id', null=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now=True)


class Share(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_id')
    like = models.ManyToManyField(User, related_name='like', through='Share_Like')
    comment = models.ManyToManyField(User, related_name='comment', through='Share_Comment')
    message = models.TextField()
    image = models.FileField(upload_to=settings.STATIC_URL+'uploads/')
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now=True)


class Share_Like(models.Model):
    share = models.ForeignKey(Share, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


class Share_Comment(models.Model):
    share = models.ForeignKey(Share, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now=True)

signup/signupApp/views.py
import os
import re

from django.core.urlresolvers import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.views.decorators.csrf import csrf_exempt
import urls

from .models import *


@csrf_exempt
def login(request):
    if request.session.get('uid'):
        return HttpResponseRedirect(reverse('signupApp:home'))
    elif request.POST:
        email = request.POST['txt_email']
        password = request.POST['txt_password']
        flag = True

        error_msg = []
        if email == "":
            error_msg.append("Email Address is required.")
            flag = False

        if password == "":
            error_msg.append("Password is required.")
            flag = False

        if flag:
            if User.objects.filter(email_id=email):
                u = User.objects.get(email_id=email)
                if u.password == password:
                    request.session['uid'] = u.id
                    print u.get_gender_display()
                    return HttpResponseRedirect(reverse('signupApp:home'))
                else:
                    return render(request, 'signupApp/login.html',
                                  {'error_message': "Email Address or Password is incorrect"})
            else:
                return render(request, 'signupApp/login.html', {'error_message':
                                                                "Email Address or Password is incorrect"})
        else:
                return render(request, 'signupApp/login.html', {'error_msg': error_msg})
    else:
        return render(request, "signupApp/login.html")


@csrf_exempt
def signup(request):
    if request.session.get('uid'):
        return HttpResponseRedirect(reverse('signupApp:home'))
    if request.POST:
        flag = True
        name = request.POST['txt_name'].lstrip()
        mobileno = request.POST['txt_mobileno'].lstrip()
        email = request.POST['txt_email'].lstrip()
        password = request.POST['txt_password'].lstrip()
        confirm_password = request.POST['txt_confirm_password'].lstrip()
        error_message = []
        # print(request.POST)

        # print User.objects.get(email_id="mayur@lintelndia.com")

        if name == "":
            error_message.append("Name is required.")
            flag = False
        elif not re.match(r'^[a-zA-Z ]+$', name):
            error_message.append("Name contains only alphabetic character.")
            flag = False

        if 'rbn_gender' not in request.POST:
            error_message.append("Gender is required.")
            flag = False
        else:
            gender = request.POST['rbn_gender']

        if mobileno == "":
            error_message.append("Mobile No is required.")
            flag = False
        elif not re.match(r'^[0-9]{10}$', mobileno):
            error_message.append("Invalid Mobile No.")
            flag = False
        elif User.objects.filter(mobile_no=mobileno):
            error_message.append("Mobile No is already registered.")
            flag = False

        if email == "":
            error_message.append("Email is required.")
            flag = False
        elif not re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
            error_message.append("Invalid Email Address.")
            flag = False
        elif User.objects.filter(email_id=email):
            error_message.append("Email Id is already registered.")
            flag = False

        if password == "":
            error_message.append("Password is required.")
            flag = False
        elif not re.match(r'^.{8,15}$', password):
            error_message.append("Password length must be between 8 to 15 characters.")
            flag = False
        elif password != confirm_password:
            error_message.append("Password & Confirm Password must be same.")
            flag = False

        if flag:
            u = User(name=name, gender=gender, mobile_no=mobileno, email_id=email, password=password)
            u.save()
            path = settings.BASE_DIR + '/signupApp' + settings.STATIC_URL + 'signupApp/UserData/' + '%d.txt' % u.id
            f = open(path, 'w')
            f.write("Id:- %d\nName:- %s\nGender:- %s\nMobile No:- %s\nEmail Id:-%s\nPassword:- ******"
                    % (u.id, name, dict(u.gender_list)[gender], mobileno, email))
            f.close()
            return render(request, "signupApp/signup.html", {'success_message': "User Register Successfully."})
            # return HttpResponseRedirect(reverse('signupApp:signup', args=("User Register Successfully.",)))
        else:
            return render(request, "signupApp/signup.html", {'error_message': error_message,
                                                             'view_state': dict(request.POST)})
    else:
        return render(request, "signupApp/signup.html")


def home(request):
    if not request.session.get('uid'):
        return HttpResponseRedirect(reverse('signupApp:login'))
    else:
        uid = request.session['uid']
        u = User.objects.get(pk=uid)
        path = settings.BASE_DIR + '/signupApp' + settings.STATIC_URL + 'signupApp/UserData/' + '%d.txt' % u.id
        if os.path.isfile(path):
            f = open(path, 'r')
            content = f.read()
        else:
            content = "Sorry, currently no data available.."
        return render(request, "signupApp/home.html", {"content": content})


def contacts(request):
    from django.core.urlresolvers import RegexURLResolver, RegexURLPattern

    view_list = []

    def get_all_view_names(urlpatterns):
        for pattern in urlpatterns:
            if isinstance(pattern, RegexURLResolver):
                get_all_view_names(pattern.url_patterns)
            elif isinstance(pattern, RegexURLPattern):
                print pattern.callback.func_name
                view_name = pattern.callback.func_name
                view_list.append(view_name)

    # get_all_view_names(urls.urlpatterns)

    def show_urls(urllist):
        for entry in urllist:
            view_list.append(entry.callback.func_name)
            if hasattr(entry, 'url_patterns'):
                show_urls(entry.url_patterns)
        return view_list

    show_urls(urls.urlpatterns)

    print view_list

    if not request.session.get('uid'):
        return HttpResponseRedirect(reverse('signupApp:contacts'))
    else:
        uid = request.session['uid']
        u = User.objects.get(pk=uid)
        contact_lst = Contact_List.objects.raw('select * from signupApp_contact_list WHERE (contact_from_user_id = %s or contact_to_user_id = %s)', [u.id, u.id])
        for c in contact_lst:
            print c.message
        return render(request, "signupApp/contacts.html")


def logout(request):
    if not request.session.get('uid'):
        return HttpResponseRedirect(reverse('signupApp:login'))
    else:
        del request.session['uid']
        return HttpResponseRedirect(reverse('signupApp:login'))

signup/signupApp/templates/signupApp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>{% block title %}{% endblock %}</title>
    <!-- BOOTSTRAP  STYLE CSS -->
    <link href="{% static 'signupApp/assets/css/bootstrap.css' %}" rel="stylesheet"/>
    <!-- FONT AWESOME STYLE CSS -->
    <link href="{% static 'signupApp/assets/css/font-awesome.css' %}" rel="stylesheet"/>
    <script src="{% static 'signupApp/assests/js/jquery.textarea_autosize.min.js' %}"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
</head>
<body style="font-family:Verdana">
<div style="padding-top: 18px;" class="container">
    <div class="row ">
    <!--
        <h3 class="text-center" style="color: orange">Notify Me </h3>
        <br/>
        <ul class="text-center mainMenu">
            <li id="menuHome"><a href="{% url 'signupApp:home' %}">HOME</a></li>
            <li id="menuContacts"><a href="{% url 'signupApp:contacts' %}">CONTACTS</a></li>
            <li id="menuChat"><a href="chat.html">CHAT</a></li>
            <li id="menuLogout"><a href="{% url 'signupApp:logout' %}">LOGOUT</a></li>
        </ul>
        <br/><br/>
        -->
        <div class="col-md-3">
                   <div class="panel panel-primary">
                        <div class="panel-heading">
                            MY PROFILE
                        </div>

                        <div class="panel-body contactList">
                            <ul class="media-list">

                                <li class="media active">

                                    <div class="media-body">

                                        <div class="media">
                                            <a class="pull-left" href="#">
                                                <img class="media-object img-circle" style="max-height:45px;"
                                                     src="{% static 'signupApp/assets/img/user.png' %}"/>
                                            </a>
                                            <div class="media-body">
                                                <h5>{{ name }} (<a href="{% url 'signupApp:logout' %}">LOGOUT</a>)</h5>

                                                <small class="text-muted">Online</small>
                                            </div>
                                        </div>

                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
    <div class="col-md-9">
        <h3 class="text-center" style="color: orange;font-size: 55px;">Notify Me </h3>
    </div>
    </div>
<div class="row ">
                {% block content %}{% endblock %}
                {% block footer %}{% endblock %}
            </div>
        </div>
</body>
</html>

signup/signupApp/templates/signupApp/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Notify Me - Contacts
{% endblock %}

{% block content %}
    <style>
        .contactList {
            padding: 0px;
        }

        .contactList li {
            cursor: pointer;
            padding: 5px 5px 5px 15px;
        }

        .contactList li:hover {
            background-color: rgba(243, 194, 103, 0.83);
        }

        .contactList-active {
            background-color: rgba(243, 194, 103, 0.83);
        }

        .contactList h5 {
            margin-bottom: 0px;
        }

        .contactList ul {
            margin-bottom: 0px;
        }

        .nav-tabs li a {
            color: black;
        }

        .btn-group-justified a {
            padding: 10px;
        }
    </style>
    <script>
        $(function () {
            $("#menuContacts a").addClass('menu-active');

            jQuery.each(jQuery('textarea[data-autoresize]'), function () {
                var offset = this.offsetHeight - this.clientHeight;

                var resizeTextarea = function (el) {
                    jQuery(el).css('height', 'auto').css('height', el.scrollHeight + offset);
                };
                jQuery(this).on('keyup input', function () {
                    resizeTextarea(this);
                }).removeAttr('data-autoresize');
            });
        });
    </script>
    <div class="col-md-3">
        <div class="panel panel-primary">
            <!--
            <ul class="panel-heading nav nav-tabs" style="padding: 0px;">
              <li class="active"><a href="#">Recent</a></li>
              <li><a href="#">Contacts</a></li>
              <li><a href="#">Group</a></li>
            </ul>
                -->
            <div style="padding: 0px;" class="panel-heading btn-group btn-group-justified">
                <a href="#" class="btn btn-warning">Recent</a>
                <a href="#" class="btn btn-warning">Contacts</a>
                <a href="#" class="btn btn-warning">Group</a>
            </div>

            <div class="panel-body contactList">
                <ul class="media-list">

                    <li class="media active">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.png' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Mayur Ariwala </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.gif' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Lalit </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.png' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Mayur Ariwala </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.gif' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Lalit </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.png' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Mayur Ariwala </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle" style="max-height:45px;"
                                         src="{% static 'signupApp/assets/img/user.gif' %}"/>
                                </a>
                                <div class="media-body">
                                    <h5>Lalit </h5>

                                    <small class="text-muted">Active From 3 hours</small>
                                </div>
                            </div>

                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="col-md-9">
        <div class="panel panel-info">
            <div class="panel-heading">
                MAYUR ARIWALA
            </div>
            <div class="panel-body">
                <ul class="media-list">

                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle "
                                         src="{% static 'signupApp/assets/img/user.gif' %}"/>
                                </a>
                                <div class="media-body">
                                    dgsdg gsdagasdgas dgsgasdfgdg sdgsgsg sgsgs gsg sgsg sg sg s g sgere3toterte
                                    eotjetoeo
                                    edgedseg gwetgwe4tmet etgetetrtryt hrgy6errsedf tye5rt
                                    <br/>
                                    <small class="text-muted">Lalit | 4th Feb at 2:00pm</small>
                                    <hr/>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-right" href="#">
                                    <img class="media-object img-circle "
                                         src="{% static 'signupApp/assets/img/user.png' %}"/>
                                </a>
                                <div class="media-body text-right">
                                    dgsdg gsdagasdgas dgsgasdfgdg sdgsgsg sgsgs gsg sgsg sg sg s g sgere3toterte
                                    eotjetoeo
                                    edgedseg gwetgwe4tmet etgetetrtryt hrgy6errsedf tye5rt
                                    <br/>
                                    <small class="text-muted pull-right">4th Feb at 2:00pm</small>
                                    <br/>
                                    <hr/>
                                </div>
                            </div>

                        </div>
                    </li>
                    <li class="media">

                        <div class="media-body">

                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object img-circle "
                                         src="{% static 'signupApp/assets/img/user.gif' %}"/>
                                </a>
                                <div class="media-body">
                                    dgsdg gsdagasdgas dgsgasdfgdg sdgsgsg sgsgs gsg sgsg sg sg s g sgere3toterte
                                    eotjetoeo
                                    edgedseg gwetgwe4tmet etgetetrtryt hrgy6errsedf tye5rt
                                    <br/>
                                    <small class="text-muted">Lalit | 4th Feb at 2:00pm</small>
                                    <hr/>
                                </div>
                            </div>

                        </div>
                    </li>
                </ul>
            </div>
            <div class="panel-footer">
                <div class="input-group">
                    <textarea type="text" class="form-control" placeholder="Enter Message" id="txtMessage"
                              name="txtMessage" data-autoresize rows="1"
                              style="resize: none; min-height: 34px;"></textarea>
                                    <span class="input-group-btn" style="vertical-align: top;">
                                        <button class="btn btn-info" type="button">SEND</button>
                                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

signup/signupApp/templates/signupApp/home.html
{% extends "base.html" %}

{% block title %}
    Notify Me
{% endblock %}

{% block content %}
    <style>
        .pre-file
        {
            color: orange !important;
            background-color: black !important;
            padding: 10px !important;
            margin-top: 25px !important;
        }
    </style>
    <script>
        $(function(){
            $("#menuHome a").addClass('menu-active');
        });
    </script>
    <div><pre class="pre-file">{{ content }}</pre></div>
{% endblock %}

signup/signupApp/templates/signupApp/login.html
<style>
    .div-login
    {
        text-align: center;
        position: absolute;
        top: 25%;
        left: 0;
        right: 0;
        background-color: #ccc;
        margin: auto;
    }
    .frm-login
    {
        background-color: #79aec8;
        border-radius: 3px;
        padding: 10px;
        width: 210px;
        margin: auto
    }
    .frm-login input
    {
        margin-bottom: 10px;
    }
    .error_msg_list
    {
        color: red;
        width: 250px;
        margin: auto;
        text-align: left;
    }
</style>
<body class="div-login">
    <h1>Login</h1>
    <form action="{% url 'signupApp:login' %}" class="frm-login" method="post">
        <input type="text" name="txt_email" id="txt_email" placeholder="Email Address" width="100%" />
        <br />
        <input type="password" name="txt_password" id="txt_password" placeholder="Password" width="100%" />
        <br />
        <input type="submit" name="btn_login" id="btn_login" value="Login" />
    </form>
    <br />
    <a href="{% url 'signupApp:signup' %}">Signup</a>
    <br />
    <br />
    <p style="color: red">{{ error_message}}</p>
    <ul class="error_msg_list">
        {% for msg in error_msg %}
            <li>{{ msg }}</li>
        {% endfor %}
    </ul>
</body>

signup/signupApp/templates/signupApp/signup.html
<style>
    .div-signup
    {
        position: absolute;
        margin: auto;
        top: 5%;
        right: 0;
        left: 0;
        width: auto;
        height: auto;
        background-color: #ccc;
        text-align: center;
    }
    .frm-signup
    {
        background-color: #79aec8;
        border-radius: 3px;
        width: 210px;
        padding: 10px;
        margin: auto
    }
    .frm-signup input
    {
        margin-bottom: 15px;
    }
    .error_msg_list
    {
        color: red;
        width: 250px;
        margin: auto;
        text-align: left;
    }
</style>
<body class="div-signup">
    <h1>Signup</h1>
    {% comment %}

    {% endcomment %}
    <form action="{% url 'signupApp:signup' %}" class="frm-signup" method="post">
        <input type="text" name="txt_name" id="txt_name" placeholder="Name" width="100%" value="{{ view_state.txt_name.0 }}" />
        <br />
        <input type="radio" name="rbn_gender" id="rbn_male" value="M" width="100%" {% if view_state.rbn_gender.0 == 'M' %}checked{% endif %} /> <label for="rbn_male">Male</label>
        <input type="radio" name="rbn_gender" id="rbn_female" value="F" width="100%" {% if view_state.rbn_gender.0 == 'F' %}checked{% endif %} /> <label for="rbn_female">Female</label>
        <br />
        <input type="text" name="txt_mobileno" id="txt_mobileno" placeholder="Mobile No" maxlength="10" width="100%" value="{{ view_state.txt_mobileno.0 }}" />
        <br />
        <input type="text" name="txt_email" id="txt_email" placeholder="Email Address" width="100%" value="{{ view_state.txt_email.0 }}" />
        <br />
        <input type="password" name="txt_password" id="txt_password" placeholder="Password" width="100%" />
        <br />
        <input type="password" name="txt_confirm_password" id="txt_confirm_password" placeholder="Confirm Password" width="100%" />
        <br />
        <input type="submit" name="btn_signup" id="btn_signup" value="Signup" />
    </form>
    <br />
    <a href="{% url 'signupApp:login' %}">Login</a>
    <br />
    <br />
    <p style="color: green">{{ success_message }}</p>
    {% if error_message > 0 %}
        <ul class="error_msg_list">
            {% for msg in error_message %}
                <li>{{ msg }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</body>